name: 'Deploy artifacts'

inputs:
  token:
    description: "GitHub token"
    required: true
  nightly:
    description: "Boolean string ('true'/'false')"
    required: true
  release_dir:
    description: "Path to the release directory"
    required: true
  spacer_release_dir:
    description: "Path to the spacer_net release directory"
    required: true

runs:
  using: composite
  steps:
    - name: Delete old nightly
      if: ${{ inputs.nightly == 'true' }}
      shell: bash
      run: |
        gh release delete nightly --yes --cleanup-tag || echo "No nightly release found to delete"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Create nightly release
      if: ${{ inputs.nightly == 'true' }}
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        allowUpdates: true
        artifacts: "${{ inputs.release_dir }}.zip,${{ inputs.spacer_release_dir }}.zip"
        generateReleaseNotes: true
        name: Nightly
        prerelease: true
        removeArtifacts: true
        tag: nightly
        token: ${{ inputs.token }}

    - name: Create regular release
      if: ${{ inputs.nightly != 'true' }}
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      with:
        allowUpdates: true
        artifacts: "${{ inputs.release_dir }}.zip,${{ inputs.spacer_release_dir }}.zip"
        generateReleaseNotes: true
        token: ${{ inputs.token }}
