name: Setup env vars
description: Sets up the environment vars required for packaging and releasing

inputs:
  nightly:
    description: Defines if nightly or regular release (case sensitive String representation of Boolean)
    required: true

runs:
  using: composite
  steps:
    - name: Set nightly env vars
      if: ${{ inputs.nightly == 'true' }}
      run: |
        $shortHash = $Env:GITHUB_SHA.Substring(0, 9)
        $dirName = "GD3D11-git-$shortHash"
        echo "Hash: ${shortHash}"
        echo "Directory: ${dirName}"
        echo "RELEASE_VERSION=${$shortHash}" >> $Env:GITHUB_ENV
        echo "RELEASE_DIR=${dirName}" >> $Env:GITHUB_ENV
        echo "SPACER_RELEASE_DIR=SpacerNET-${dirName}" >> $Env:GITHUB_ENV
      shell: pwsh

    - name: Set release env vars
      if: ${{ inputs.nightly != 'true' }}
      run: |
        $tagName = $Env:GITHUB_REF -replace 'refs/tags/', ''
        $dirName = "GD3D11-${tagName}"
        echo "Tag: ${tagName}"
        echo "Directory: ${dirName}"
        echo "RELEASE_VERSION=${tagName}" >> $Env:GITHUB_ENV
        echo "RELEASE_DIR=${dirName}" >> $Env:GITHUB_ENV
        echo "SPACER_RELEASE_DIR=SpacerNET-${dirName}" >> $Env:GITHUB_ENV
      shell: pwsh
