name: 'Calculate path names'

inputs:
  nightly:
    description: "Boolean string ('true'/'false')"
    required: true

outputs:
  release_dir:
    description: "The main directory name"
    value: ${{ steps.calc.outputs.dir_name }}
  spacer_release_dir:
    description: "The spacer directory name"
    value: ${{ steps.calc.outputs.spacer_dir }}

runs:
  using: composite
  steps:
    - name: Calculate path name outputs
      id: calc
      shell: pwsh
      run: |
        if ("${{ inputs.nightly }}" -eq "true") {
            $version = $env:GITHUB_SHA.Substring(0, 9)
            $dirName = "GD3D11-git-$version"
        } else {
            $version = $env:GITHUB_REF -replace 'refs/tags/', ''
            $dirName = "GD3D11-$version"
        }

        $spacerDir = "SpacerNET-$dirName"

        "dir_name=$dirName" >> $env:GITHUB_OUTPUT
        "spacer_dir=$spacerDir >> $env:GITHUB_OUTPUT
