name: 'Package artifact'

inputs:
  include-spacer-net:
    description: "Defines if spacer_net artifact should be included (case sensitive String representation of Boolean)"
    required: true
  release_dir:
    description: "Path to the release directory"
    required: true
  spacer_release_dir:
    description: "Path to the spacer_net release directory"
    required: true

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v7

    - name: Prepare Release Structure
      shell: pwsh
      run: |
        function Copy-Assets($dest) {
            New-Item -Path "$dest/GD3D11/Bin" -ItemType Directory -Force
            Copy-Item -Path "D3D11Engine/Shaders/*" -Destination "$dest/GD3D11/shaders/" -Recurse -Force
            Copy-Item -Path "blobs/Fonts" -Destination "$dest/GD3D11/Fonts/" -Recurse -Force
            Copy-Item -Path "blobs/Meshes" -Destination "$dest/GD3D11/Meshes/" -Recurse -Force
            Copy-Item -Path "blobs/Textures" -Destination "$dest/GD3D11/Textures/" -Recurse -Force
            Copy-Item -Path "blobs/libs/*" -Destination "$dest/" -Recurse -Force
            Copy-Item -Path "blobs/bin/wine-d2d1.dll" -Destination "$dest/GD3D11/Bin/d2d1.dll" -Force
        }

        Copy-Assets "${{ inputs.release_dir }}"
        
        Copy-Item -Path "Release/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g2a.dll"
        Copy-Item -Path "Release_AVX/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g2a_avx.dll"
        Copy-Item -Path "Release_AVX2/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g2a_avx2.dll"
        Copy-Item -Path "Release_G1/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g1.dll"
        Copy-Item -Path "Release_G1_AVX/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g1_avx.dll"
        Copy-Item -Path "Release_G1_AVX2/ddraw.dll" -Destination "${{ inputs.release_dir }}/GD3D11/Bin/g1_avx2.dll"
        Copy-Item -Path "Launcher/ddraw.dll" -Destination "${{ inputs.release_dir }}/"

        if ("${{ inputs.include-spacer-net }}" -eq "true") {
            Copy-Assets "${{ inputs.spacer_release_dir }}"
            Copy-Item -Path "Spacer_NET/ddraw.dll" -Destination "${{ inputs.spacer_release_dir }}/"
        }

    - name: Create ZIPs
      shell: pwsh
      run: |
        Compress-Archive -Path "${{ inputs.release_dir }}/*" -DestinationPath "${{ inputs.release_dir }}.zip" -Force

        if ("${{ inputs.include-spacer-net }}" -eq "true") {
            Compress-Archive -Path "${{ inputs.spacer_release_dir }}/*" -DestinationPath "${{ inputs.spacer_release_dir }}.zip" -Force
        }

    - name: Upload Zip Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: final-packages
        path: "*.zip"
        compression-level: 0
        retention-days: 2
