name: 'Package artifacts'

inputs:
  nightly:
    description: "Boolean string ('true'/'false')"
    required: true
  include-spacer-net:
    description: "Defines if spacer_net artifact should be included"
    required: true
  artifact-name:
    description: "Name of the artifact that will be uploaded"
    required: true

runs:
  using: composite
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v7

    - name: Calculate path names
      id: paths
      shell: pwsh
      run: |
        if ("${{ inputs.nightly }}" -eq "true") {
          $shortHash = $env:GITHUB_SHA.Substring(0, 9)
          $dirName = "GD3D11-git-$shortHash"
        } else {
          $rawName = $env:GITHUB_REF -replace '^refs/(tags|heads)/', ''
          $safeName = $rawName -replace '/', '-'
          $dirName = "GD3D11-$safeName"
        }

        "dir_name=$dirName" >> $env:GITHUB_OUTPUT
        "spacer_dir=SpacerNET-$dirName" >> $env:GITHUB_OUTPUT

    - name: Prepare Release Structure
      shell: pwsh
      run: |
        $relDir = "${{ steps.paths.outputs.dir_name }}"
        $spacerDir = "${{ steps.paths.outputs.spacer_dir }}"

        function Copy-Assets($dest) {
          New-Item -Path "$dest/GD3D11/Bin" -ItemType Directory -Force
          Copy-Item -Path "D3D11Engine/Shaders/*" -Destination "$dest/GD3D11/shaders/" -Recurse -Force
          Copy-Item -Path "blobs/Fonts" -Destination "$dest/GD3D11/Fonts/" -Recurse -Force
          Copy-Item -Path "blobs/Meshes" -Destination "$dest/GD3D11/Meshes/" -Recurse -Force
          Copy-Item -Path "blobs/Textures" -Destination "$dest/GD3D11/Textures/" -Recurse -Force
          Copy-Item -Path "blobs/libs/*" -Destination "$dest/" -Recurse -Force
          Copy-Item -Path "blobs/bin/wine-d2d1.dll" -Destination "$dest/GD3D11/Bin/d2d1.dll" -Force
        }

        Copy-Assets $relDir

        Copy-Item -Path "Release/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g2a.dll"
        Copy-Item -Path "Release_AVX/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g2a_avx.dll"
        Copy-Item -Path "Release_AVX2/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g2a_avx2.dll"
        Copy-Item -Path "Release_G1/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g1.dll"
        Copy-Item -Path "Release_G1_AVX/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g1_avx.dll"
        Copy-Item -Path "Release_G1_AVX2/ddraw.dll" -Destination "$relDir/GD3D11/Bin/g1_avx2.dll"
        Copy-Item -Path "Launcher/ddraw.dll" -Destination "$relDir/"

        if ("${{ inputs.include-spacer-net }}" -eq "true") {
          Copy-Assets $spacerDir
          Copy-Item -Path "Spacer_NET/ddraw.dll" -Destination "$spacerDir/"
        }

    - name: Create ZIPs
      shell: pwsh
      run: |
        $relDir = "${{ steps.paths.outputs.dir_name }}"
        $spacerDir = "${{ steps.paths.outputs.spacer_dir }}"

        7z a -tzip "$relDir.zip" "./$relDir/*"

        if ("${{ inputs.include-spacer-net }}" -eq "true") {
          7z a -tzip "$spacerDir.zip" "./$spacerDir/*"
        }

    - name: Upload Zip Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: "*.zip"
        compression-level: 0
        retention-days: 2
