name: 'Package artifacts'

inputs:
  nightly:
    description: "Boolean string ('true'/'false')"
    required: true
  artifact-name:
    description: "Name of the artifact that will be uploaded"
    required: true

runs:
  using: composite
  steps:
    - name: Download build artifacts
      id: download-artifacts
      uses: actions/download-artifact@v7
      with:
        path: downloaded-artifacts
        merge-multiple: true

    - name: Calculate artifact path name
      id: calc-path
      shell: pwsh
      run: |
        if ("${{ inputs.nightly }}" -eq "true") {
          $shortHash = $env:GITHUB_SHA.Substring(0, 9)
          $dirName = "GD3D11-git-$shortHash"
        } else {
          $rawName = $env:GITHUB_REF -replace '^refs/(tags|heads)/', ''
          $safeName = $rawName -replace '/', '-'
          $dirName = "GD3D11-$safeName"
        }

        "dir_name=$dirName" >> $env:GITHUB_OUTPUT

    - name: Prepare Release Structure
      shell: pwsh
      run: |
        $relDir = "${{ steps.calc-path.outputs.dir_name }}"
        $artifactDir = "${{ steps.download-artifacts.inputs.path }}"
        $binDir = "$relDir/GD3D11/Bin"

        New-Item -Path $binDir -ItemType Directory -Force
        
        Copy-Item -Path "D3D11Engine/Shaders/*" -Destination "$relDir/GD3D11/shaders/" -Recurse -Force
        Copy-Item -Path "blobs/Fonts" -Destination "$relDir/GD3D11/Fonts/" -Recurse -Force
        Copy-Item -Path "blobs/Meshes" -Destination "$relDir/GD3D11/Meshes/" -Recurse -Force
        Copy-Item -Path "blobs/Textures" -Destination "$relDir/GD3D11/Textures/" -Recurse -Force
        Copy-Item -Path "blobs/libs/*" -Destination "$relDir/" -Recurse -Force
        Copy-Item -Path "blobs/bin/wine-d2d1.dll" -Destination "$relDir/GD3D11/Bin/d2d1.dll" -Force

        Copy-Item -Path "$artifactDir/*" -Destination $binDir -Force
        Move-Item -Path "$binDir/ddraw.dll" -Destination "$relDir/" -Force

    - name: Create final Zip
      shell: pwsh
      run: |
        $relDir = "${{ steps.path.outputs.dir_name }}"
        7z a -tzip "$relDir.zip" "./$relDir/*"

    - name: Upload Zip artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: "*.zip"
        compression-level: 0
        retention-days: 2
